events/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from events import views as views_events


urlpatterns = [
    path('minicurso/<int:pk>/', views_events.EventDetailView.as_view(), name='event-detail'),
    path('meus-minicursos/', login_required(views_events.MyRegistrationsListView.as_view()), name='my-events'),
    path('minicurso/novo/', login_required(views_events.EventCreateView.as_view()), name='event-create'),
    path('minicurso/<int:pk>/turmas/', login_required(views_events.GroupListView.as_view()), name='group-list'),
    path('minicurso/inscricao/<int:pk>/', login_required(views_events.EventRegistrationView.as_view()), name="event-registration"),
    path('minicurso/cancelar-inscricao/<int:pk>/', login_required(views_events.EventRegistrationDeleteView.as_view()), name="event-delete-registration"),
    path('minicurso/<int:pk>/participantes/', login_required(views_events.RegistrationsListView.as_view()), name="registrations-list"),
    path('minicurso/<int:pk>/participantes/imprimir/', login_required(views_events.RegistrationsPDFView.as_view()), name="registrations-list-pdf"),
    path('minicurso/presenca/<int:pk>/', login_required(views_events.RegistrationPresentView.as_view()), name="registration-present"),
    path('minicurso/ausencia/<int:pk>/', login_required(views_events.RegistrationAbsentView.as_view()), name="registration-absent"),
    path('minicurso/<int:pk>/turmas/nova/', login_required(views_events.GroupCreateView.as_view()), name='group-create'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User

def get_name(self):
    return self.get_full_name()

User.add_to_class("__str__", get_name)

CHOICES_STATUS_EVENT = (
    (1, "Submetido"),
    (2, "Aprovado"),
    (3, "Não aprovado"),
)

CHOICES_STATUS_REGISTRATION = (
    (1, "Inscrito"),
    (2, "Presente"),
    (3, "Ausente"),
)

CHOICES_WORKLOADS = (
    (1, '2 horas'),
    (2, '4 horas'),
)

CHOICES_SHIFTS_4 = (
    (1, '04/10/2018 - 13:15 às 16:50'),
    (2, '04/10/2018 - 19:00 às 22:30'),
)

CHOICES_SHIFTS_2 = (
    (11, '04/10/2018 - 13:15 às 14:55'),
    (12, '04/10/2018 - 15:10 às 16:50'),
    (13, '04/10/2018 - 19:00 às 20:40'),
    (14, '04/10/2018 - 20:50 às 22:30'),
    (15, '04/10/2018 - 17:00 às 19:00'),
)

CHOICES_SHIFTS = CHOICES_SHIFTS_2 + CHOICES_SHIFTS_4


class Event(models.Model):

    class Meta:
        verbose_name = 'Minicurso'
        verbose_name_plural = 'Minicursos'

    title = models.CharField(max_length=200, verbose_name='Título')
    description = models.TextField(verbose_name='Resumo (Breve descrição)', help_text='Paragráfo único com no máximo 100 palavras.')
    goal = models.TextField(verbose_name='Objetivo')
    public = models.CharField(max_length=200, verbose_name='Público Alvo')
    vacancies = models.PositiveIntegerField(verbose_name='Número Máximo de Participantes')
    requirements = models.TextField(verbose_name='Pré-requisitos', blank=True, null=True)
    materials = models.TextField(verbose_name='Recursos necessários', blank=True, null=True)
    workload = models.PositiveIntegerField(verbose_name='Carga Horária', choices=CHOICES_WORKLOADS)
    status = models.IntegerField(choices=CHOICES_STATUS_EVENT, default=1, verbose_name='Status')
    author = models.ForeignKey(User, verbose_name='Autor', on_delete=models.PROTECT, related_name='author_events')
    co_authors = models.ManyToManyField(User, verbose_name='Co-autores', related_name='co_authors_events', blank=True)
    supervisor = models.ForeignKey(User, verbose_name='Orientador', on_delete=models.PROTECT, related_name='supervised_events', blank=True, null=True)

    def __str__(self):
        return self.title

    def get_author(self):
        authors = [u.get_full_name() for u in self.co_authors.all()]
        authors += [self.author.get_full_name()]
        if self.supervisor:
            authors += [self.supervisor.get_full_name()]
        return ', '.join(authors)


class Group(models.Model):

    class Meta:
        verbose_name = "Turma"
        verbose_name_plural = "Turmas"
        unique_together = ['event', 'shift']

    event = models.ForeignKey(Event, on_delete=models.PROTECT, related_name='groups')
    shift = models.PositiveIntegerField(choices=CHOICES_SHIFTS, verbose_name='Data')
    local = models.CharField(max_length=100, verbose_name='Local', null=True, blank=True)

    def __str__(self):
        return '%s - %s' % (self.event.title, self.get_shift_display())


class Registration(models.Model):

    class Meta:
        unique_together = (('group', 'user'),)
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'

    group = models.ForeignKey(Group, on_delete=models.PROTECT, related_name='registrations')
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='registrations')
    status = models.IntegerField(choices=CHOICES_STATUS_REGISTRATION, default=1)

    def __str__(self):
        return self.group.event.title + ' - ' + self.user.first_name

events/forms.py
from django import forms
from django_select2.forms import Select2Widget, Select2MultipleWidget

from events.models import Event, Group
from django.contrib.auth.models import User

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ('status', 'local')
        widgets = {
            'supervisor': Select2Widget,
            'co_authors': Select2MultipleWidget,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        users = User.objects.filter(is_superuser=False)
        self.fields['co_authors'].choices = [(u.id, u.get_full_name()) for u in users]
        self.fields['supervisor'].choices = [(u.id, u.get_full_name()) for u in users.filter(groups__name='servidores')]
        self.fields['supervisor'].choices += [('', '--------')]



class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        exclude = ('event', 'local', 'hour')
        widgets = {
            'datetime': forms.DateInput(attrs={'type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        self.choices = kwargs.pop('choices', None)
        super().__init__(*args, **kwargs)
        self.fields['shift'].choices = self.choices

events/views.py
from datetime import date

from easy_pdf.views import PDFTemplateResponseMixin
from django.views.generic.edit import CreateView
from django.views.generic import View, ListView, DetailView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.http import HttpResponse
import csv

from events.models import Event, Registration, Group, CHOICES_SHIFTS_2, CHOICES_SHIFTS_4
from events.forms import EventForm, GroupForm


class EventCreateView(CreateView):
    model = Event
    template_name = 'events/event-create.html'
    form_class = EventForm

    def get_success_url(self):
        return reverse_lazy('group-list', args=(self.object.id,))

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial['author'] = self.request.user.pk
        return initial


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event-detail.html'

    def get_context_data(self, *args, **kwargs):
        event = self.get_object()
        user = self.request.user
        try:
            context = super().get_context_data(*args, **kwargs)
            context['registration'] = Registration.objects.get(group__event=event, user=user)
        except:
            context['registration'] = False
        return context



class EventRegistrationView(DetailView):
    model = Group

    def get(self, request, *args, **kwargs):
        Registration.objects.create(group=self.get_object(), user=request.user)
        return redirect('event-detail', self.get_object().event.pk)

class EventRegistrationDeleteView(DetailView):
    model = Group

    def get(self, request, *args, **kwargs):
        Registration.objects.get(group=self.get_object(), user=request.user).delete()
        return redirect('event-detail', self.get_object().event.pk)

class MyRegistrationsListView(ListView):
    model = Registration
    template_name = 'events/my-events.html'


class GroupListView(DetailView):
    model = Event
    template_name = 'groups/group-list.html'


class GroupCreateView(DetailView, CreateView):
    model = Event
    template_name = 'groups/group-create.html'
    form_class = GroupForm

    def get_success_url(self):
        return reverse_lazy('group-list', args=(self.get_object().id,))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        event = self.get_object()
        EXCLUDE = [(e.shift, e.get_shift_display()) for e in event.groups.all()]
        if event.workload == 1:
            kwargs['choices'] = set(CHOICES_SHIFTS_2) - set(EXCLUDE)
        else:
            kwargs['choices'] = set(CHOICES_SHIFTS_4) - set(EXCLUDE)
        return kwargs

    def get(self, request, *args, **kwargs):
        if self.request.user == self.get_object().author:
            return super().get(request, *args, **kwargs)
        return redirect('event-detail', self.get_object().event.pk)

    def form_valid(self, form):
        form.instance.event = self.get_object()
        return super().form_valid(form)


class RegistrationUpdateView(DetailView):
    model = Registration
    status = 1

    def get(self, request, *args, **kwargs):
        registration = self.get_object()
        registration.status = self.status
        registration.save()
        return redirect('registrations-list', registration.group.id)


class RegistrationPresentView(RegistrationUpdateView):
    status = 2


class RegistrationAbsentView(RegistrationUpdateView):
    status = 3


class RegistrationsListView(DetailView):
    model = Group
    template_name = "events/registrations-list.html"
    pdf = False

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        event = self.get_object()
        context['registrations'] = Registration.objects.filter(group=self.get_object()).order_by('user__first_name')
        context['pdf'] = self.pdf
        return context

    def post(self, request, *args, **kwargs):
        user = User.objects.get(username=request.POST['cpf'])
        registration = Registration.objects.get(user=user, group=self.get_object())
        registration.status = 2
        registration.save()
        return super().get(request, *args, **kwargs)


class RegistrationsPDFView(RegistrationsListView, PDFTemplateResponseMixin):
    template_name = 'events/registrations-list-pdf.html'
    pdf = True


class RegistrationDetailView(DetailView, PDFTemplateResponseMixin):
    model = Registration
    template_name = "registrations-detail-pdf.html"
    page_size = 100
    page_size_query_param = 'page_size'
    max_page_size = 10000

events/templates/events/event-create.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
  <section>
    <div class="container">
      <h1>Enviar proposta</h1>
      <form method="POST">
        {% csrf_token %}
        <p><b>Autor: </b>{{ request.user.get_full_name }}</p>
        {{ form|bootstrap }}
        <div align="right">
          <a class="btn btn-default" href="{% url 'home' %}">Cancelar</a>
          <input class="btn btn-success" type="submit" value="Salvar">
        </div>
      </form>
    </div>
  </section>
{% endblock content %}

{% block js %}
  <script type="text/javascript">
    $('#id_author').parent().parent().hide();
    $( document ).ready(function() {
      $('#id_co_authors').select2({ maximumSelectionLength: 5, "language": "pt-BR"});

    });
  </script>
{% endblock js %}

events/templates/events/event-detail.html
{% extends "base.html" %}
{% load static %}
{% load check_conflict %}

{% block page_title %}Minicurso{% endblock page_title %}

{% block content %}
  <section>
    <div class="container">
      <h2 center>{{ object.title }}</h2>
      <div class="row">
        <div class="col-md-6">
          <p><h4>Autores:</h4> {{ object.get_author }}</p>
          <p><h4>Objetivos:</h4> {{ object.goal }}</p>
          <p><h4>Descrição:</h4> {{ object.description}}</p>
        </div>
        <div class="col-md-6">
          <p><h4>Público Alvo:</h4> {{ object.public }}</p>
          <p><h4>Pré-requisitos:</h4> {{ object.requirements }}</p>
          <p><h4>Carga Horária:</h4> {{ object.get_workload_display }}</p>
          <p><h4>Vagas:</h4> {{ object.vacancies }}</p>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Turma</th>
              <th>Local</th>
              <th>Inscrição</th>
              {% if request.user.is_superuser %}
                <th>Gerenciar Registros</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for group in event.groups.all %}
              <tr>
                <td>{{ group }}</td>
                <td>{{ group.local|default_if_none:"A definir" }}</td>
                <td>
                  {% if registration %}
                    {% if registration.group == group %}
                      <a class="btn btn-success" href="{% url 'event-delete-registration' group.id %}" >Inscrito (Clique aqui para CANCELAR)</a>
                    {% else %}
                      <button class="btn btn-success" disabled>Inscrito em outra turma</button>
                    {% endif %}
                  {% elif not request.user.is_authenticated %}
                    <button class="btn btn-danger" disabled>Necessário Login Para Inscrição</button>
                  {% elif group.registrations.count >= group.event.vacancies %}
                      <button class="btn btn-danger" disabled>Esgotado</button>
		              {% elif not group|check:request.user %}
                    <button class="btn btn-danger" disabled>Conflito de horário</button>
                  {% else %}
                    <a href="{% url 'event-registration' group.pk %}" class="btn btn-success btn-info">Realizar Inscrição</a>
                  {% endif %}
                </td>
                {% if request.user.is_staff or  request.user == object.author %}
                  <td><a class="btn btn-info" href="{% url 'registrations-list' group.pk %}"> Gerenciar</a></td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

events/templates/events/my-events.html
{% extends "base.html" %}

{% block content %}

<section>
  <div class="container">
    <h1>Meus eventos</h1>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <h3>Minhas Inscrições</h3>
        <table class="table">
          <thead>
            <th>Turma</th>
            <th>Data</th>
            <th>Local</th>
          </thead>
          <tbody>
            {% for obj in request.user.registrations.all %}
              <tr>
                <td>{{ obj.group }}</td>
                <td>{{ obj.group.date }}</td>
                <td>{{ obj.group.local }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="col-md-6">
        <h3>Minhas Submissões</h3>
        <table class="table">
          <thead>
            <th>Título</th>
            <th>Tipo</th>
            <th>Status</th>
            <th>Turmas</th>
          </thead>
          <tbody>
            {% for event in request.user.author_events.all %}
              <tr>
                <td><a href="{% url 'event-detail' event.pk %}">{{ event.title }}</a></td>
                <td>Minicurso</td>
                <td>{{ event.get_status_display }}</td>
                <td><a href="{% url 'group-list' event.pk %}">turmas</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <hr>
  </div>
</section>

{% endblock content %}

events/templates/events/registrations-list-pdf.html
{% extends "easy_pdf/base.html" %}

{% block extra_style %}
   <meta http-equiv="content-type" content="text/html; charset=utf-8"> 
{% endblock %}

{% block content %}

<h3 align="center">{{ object }}</h3>
<h2 align="center">{{ object.local }}</h2>

<style type="text/css">
td, th {
	border: 1px solid black;
	padding: 5px 0px 0px 5px;
	text-align: left;
	font-family: Sans-serif;
	font-size: 12px;
	border-collapse: collapse;
	color: black;
}
h3{
	font-family: serif;
	font-size: 14px;
}
</style>

{% include "events/registrations-table-pdf.html" %}

{% endblock content %}

events/templates/events/registrations-list.html
{% extends "base.html" %}

{% block content %}
<section>
    <div class="container">
        {% include "events/registrations-table.html" %}
        <hr>
        <p align="right ">
          <a class="btn btn-success" href="{% url 'registrations-list-pdf' object.pk %}">
            Imprimir lista de presença
          </a>
      </p>
    </div>
</section>
{% endblock content %}

events/templates/events/registrations-table-pdf.html
<table class="table table-hover">
  <thead class="bg-dark">
    <tr>
      <th>Nome</th>
      <th width="300px">CPF</th>
      <th width="300px">Presença</th>
    </tr>
  </thead>
  <tbody>
    {% for object in registrations %}
    <tr>
      <td>{{ object.user.get_full_name }}</td>
      <td>{{ object.user.username }}</td>
      <td><br></td>
   </tr>
   {% endfor %}
 </tbody>
</table>

events/templates/events/registrations-table.html
<table class="table table-hover">
  <thead class="bg-dark">
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th width="350px">E-mail</th>
      <th>Status</th>
      <th>Presença</th>
      
    </tr>
  </thead>
  <tbody>
    {% for object in registrations %}
    <tr>
      <td>{{ object.user.get_full_name }}</td>
      <td>{{ object.user.username }}</td>
      <td>{{ object.user.email }}</td>
      <td>{{ object.get_status_display }}</td>
      <td>

        {% if object.status == 3 %}
        <a href="{% url 'registration-present' object.pk %}" class="btn btn-success Presenca">Presente
       </a>
       {% endif %}
       {% if object.status == 2 %}
       <a href="{% url 'registration-absent' object.pk %}" class="btn btn-danger Presenca">Ausente
       </a>
       {% endif %}

     </td>

   </tr>
   {% endfor %}
 </tbody>
</table>